### ISSUE TITLE
administration screen doesn't appear

### ISSUE THREAD

**Issue by buzter** [Keleo/CustomCSSBundle#1]
Hello,

I upgraded from kimai1 to 2 yesterday. Good work and documentation so far. Thx a lot.

I also installed CustomCSSBundle as described. But the administration screen doesn't appear for Super Admin. Do I have to change sth. not mentioned in the documentation? I don't get any errors and kimai2 works fine too. So I really have no clue where to start failure search. (Likely it's between my screen and backrest). Best regards

**Comment by kevinpapst** [comment]
Which version did you install? Plugins only work without the latest master of Kimai 2

**Comment by buzter** [comment]
Kimai2 0.8.1
CustomCSSBundle 0.1

> Plugins only work without the latest master of Kimai

Do You mean "without" or with the latest master of Kimai2?

**Comment by kevinpapst** [comment]
LOL, auto correction... with the latest master, not with 0.8.1. as written on the marketplace page

**Comment by buzter** [comment]
Ooops, didn't see that... Thx a lot!
