### ISSUE TITLE
remove colored dots not working

### ISSUE THREAD

**Issue by BeckeBauer** [Keleo/CustomCSSBundle#11]
Under the general tab, css to remove colored dots can be included. However, it's not removing the red dots in my installation

For me, the following css is working:
```
table.dataTable tr.overlapping {
    border-top: 2px dotted white;
}
```
Can you please check?

P.S.: under Kimai/plugins, CustomCCSBundel version 1.1 is still shown (was confused; thought my update went wrong)

**Comment by kevinpapst** [comment]
Forgot to bump the version number ... thanks for the reminder!
Will check the other rules and add them

**Comment by kevinpapst** [comment]
Please try https://github.com/Keleo/CustomCSSBundle/releases/tag/1.3

**Comment by BeckeBauer** [comment]
copied the new css code at https://demo-plugins.kimai.org/en/admin/custom-css 
```
/* START [general] remove-color-dots */
i.dot, span.dot {display:none !important;}
/* END [general] remove-color-dots */
```
The red dots remain see https://demo-plugins.kimai.org/en/timesheet/

**Comment by kevinpapst** [comment]
colored dots are the ones in front of customer/project/activity name.
The "red-line" between timesheets is the indicator for overlapping records.

**Comment by BeckeBauer** [comment]
my fault: though that colored dots were refering to the colored dots line around a time recored

did not know that is shows overlapping records - wanted to "get rid" of the overlapping records line not the colored dots... sorry

**Comment by BeckeBauer** [comment]
found the new css under timesheets - hide-overlapping-records; it's working perfectly, thanks

**Comment by kevinpapst** [comment]
thanks for the testing feedback!
