### ISSUE TITLE
css suggestion for the "timesheet tab"

### ISSUE THREAD

**Issue by BeckeBauer** [Keleo/CustomCSSBundle#12]
Would it be possible, if you add the following pre-defined rule under the "timesheet tab":
```
/* START active entry color */
tr.recording {
   background-color: #ffa059 !important;
}
/* END active entry color */
```
It shows the active entry in a different color which I think you suggested some time ago and which I really like since then

**Comment by kevinpapst** [comment]
Please try https://github.com/Keleo/CustomCSSBundle/releases/tag/1.3
