### ISSUE TITLE
responsive tables for weekly working hours

### ISSUE THREAD

**Issue by BeckeBauer** [Keleo/CustomCSSBundle#15]
Sometimes, I have (too) long project and/or activity names. When opening the weekly working tab, the project field and/or activity field uses most of the space (and no working time is shown):

![screenshot](https://user-images.githubusercontent.com/51003649/141448242-f2a06332-66bb-40bd-8eb4-e3af16142756.png)

It would be great to have a CSS option that would introduce a line-break or an option to scroll horizontally

**Comment by kevinpapst** [comment]
Same on demo? Which browser ... is this happening?

**Comment by BeckeBauer** [comment]
same on demo:

![image](https://user-images.githubusercontent.com/51003649/141777117-b0c58876-4109-4e3c-8fdb-d367a791ce3e.png)

I am using MS Edge

**Comment by kevinpapst** [comment]
Maybe a rule like this would help
```
#quick_entry_form .select2-container {
max-width: 250px;
}

**Comment by BeckeBauer** [comment]
it worked for me as follows:

```
.select2-container {
max-width: 200px;
}
```
Thank you!

**Comment by kevinpapst** [comment]
That rule applies to every dropdown, doesn't it?

**Comment by BeckeBauer** [comment]
I do not mind; `#quick_entry_form` upfront had no effect
