### ISSUE TITLE
Unable to generate a URL for the named route "custom_css"

### ISSUE THREAD

**Issue by p-try** [Keleo/CustomCSSBundle#19]
Hello everybody! I would like to report an error that I get after I installed this plugin.

**Steps:**
I installed this plugin in Kimai 1.30.5 by cloning the code into var/plugins/CustomCSSBundle and then running `bin/console kimai:reload --env=prod`. 

**Symptoms:**
Logging in not possible anymore. Error 500 is thrown.

**Log excerpt:**
`[2023-03-03 11:03:12] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "custom_css" as such route does not exist.")." at /opt/kimai/vendor/kevinpapst/adminlte-bundle/Resources/views/Sidebar/menu.html.twig line 8 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"custom_css\" as such route does not exist.\"). at /opt/kimai/vendor/kevinpapst/adminlte-bundle/Resources/views/Sidebar/menu.html.twig:8, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"custom_css\" as such route does not exist. at /opt/kimai/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []`

**Comment by kevinpapst** [comment]
Install the correct version, than it will work.

**Comment by p-try** [comment]
🤦  sorry about that. Thanks.
