### ISSUE TITLE
How to change application title and login-page

### ISSUE THREAD

**Issue by Collandi** [Keleo/CustomCSSBundle#8]
Hi Kevin,
I installed the Plugin and it works fineafter login.

But

1. How to change application title? (Kimai Zeiterfassung -> Custom Title)

2. Is it possible to change the Login-Page?

```
.login-page {
background:#d2d6de
} 
```
doesn't works.

THX
Andreas

**Comment by buzter** [comment]
Hi, 

I had the same issue. For me worked the following:

`
.login-logo, .register-logo {
    visibility: hidden;
}
.layout-boxed body, .layout-boxed html, body, html {
    background: #000000; 
}
.login-page, .register-page {
    background: none;
}
`

**Comment by kevinpapst** [comment]
You need the latest Kimai release 1.1. In previous versions the Custom CSS wasn't loaded on the login screen.

**Comment by kevinpapst** [comment]
And the browser title can't be changed with CSS

**Comment by kevinpapst** [comment]
And here is the docu for all the other stuff: https://www.kimai.org/documentation/branding.html

**Comment by Collandi** [comment]
Hi Kevin,
thank you very much.

> If you use these options, you should really consider to donate something back to Kimai!

For sure!

**Comment by Collandi** [comment]
> You need the latest Kimai release 1.1. In previous versions the Custom CSS wasn't loaded on the login screen.

It doesn't works in my Kimai2 installation.
I tried to use the code above to change the login background color. I cleared and warmed up the cache but nothing is changed.

Any suggestions?

**Comment by kevinpapst** [comment]
"Doesn't work" is not very descriptive ;-)
Make sure the Custom CSS plugin is loaded (check the admin screen).
Make sure the CSS rule is included in your login pages source HTML code (use "show source" in your browser).
As @buzter rules work in http://demo-plugins.kimai.org/ it must be something on your end.

**Comment by Collandi** [comment]
Hi Kevin,
first I have to tell you, we are very impressed of Kimai Timetracker. Great work and easy to use without nicknack. Thank you very much.

About my issue:
Yes, the Custom CSS Plugin is loaded and work for the screens after login but not for the login-page.

If I change the CSS rule in the browser it works.

Screenshot:
![kimai-css-login-page-browser-change](https://user-images.githubusercontent.com/23042299/62140720-c4c7d500-b2eb-11e9-9fb0-514159528997.jpg)

If I add the same css rule in the plugin:

![kimai-css-backend](https://user-images.githubusercontent.com/23042299/62140719-c4c7d500-b2eb-11e9-9346-f5a1f2c49652.jpg)

nothing is changed:

![kimai-css-login-page-with-custom-css](https://user-images.githubusercontent.com/23042299/62140721-c4c7d500-b2eb-11e9-9389-9d56df1c9c8c.jpg)

I tried with !important too without success.

What's wrong?

Best regards
Andreas

**Comment by kevinpapst** [comment]
>  Make sure the CSS rule is included in your login pages source HTML code (use "show source" in your browser).

<img width="1235" alt="Bildschirmfoto 2019-07-30 um 18 00 50" src="https://user-images.githubusercontent.com/533162/62145656-1bd1a800-b2f4-11e9-94f3-cc7fe882ae8e.png">

**Comment by Collandi** [comment]
I know. But isn't included:

![login-source](https://user-images.githubusercontent.com/23042299/62146144-12950b00-b2f5-11e9-8521-140c9c5fe852.jpg)

**Comment by kevinpapst** [comment]
Output of `bin/console kimai:version`?

**Comment by Collandi** [comment]
Kimai 2 - 1.0.1 stable (Ayumi) by Kevin Papst and contributors.

**Comment by kevinpapst** [comment]
Oh really. Come one... 
> You need the latest Kimai release 1.1. In previous versions the Custom CSS wasn't loaded on the login screen.

Not very respectful to simply ignore my answers.
