### ISSUE TITLE
plugin not found by kimai

### ISSUE THREAD

**Issue by inside54** [Keleo/CustomCSSBundle#9]
Hi there! I can't install this plugin, can you help me?

I installed Kimai locally with XAMPP (WIN 10), it works fine.
now I have moved the plugin folder to the path you indicated, but in the plugin tab of the front end I always get this answer "You have no plugins installed yet."

you can check the file path in this screenshot https://puu.sh/EyIQ1/66dcb68806.png

**Comment by inside54** [comment]
here u can check frontend https://puu.sh/EyIUX/62cd1a8d9d.png

**Comment by kevinpapst** [comment]
Compare your screenshot with the docs: 
```
/kimai/var/plugins/
├── CustomCSSBundle
```
Also you need to clear the cache.

**Comment by inside54** [comment]
You mean browser cache? I tried to clean the browser cache, but I get the same result. Also tried to stop xampp and restart the service

otherwise if you mean this:
```
cd /kimai/
bin/console cache:clear
bin/console cache:warmup
```
It looks like a linux command line

**Comment by kevinpapst** [comment]
Yes, you have to figure out how to it in Windows. I guess you need to premed php, something like:
```php bin/console cache:clear```
Or you simply delete: var/cache/prod/

And you need to fix the directory name

**Comment by inside54** [comment]
sorry i am a beginner.
I ve deleted the folder you told me but I still don't understand what's wrong with the directory name. did you mean this? https://puu.sh/EyJQO/f883702c5a.png

I tried to move the contents of the folder inside the var/plugin path (I cleaned the cache after this step), but I get the same result

**Comment by kevinpapst** [comment]
No, I mean this:
<img width="182" alt="Bildschirmfoto 2019-10-30 um 13 55 00" src="https://user-images.githubusercontent.com/533162/67859874-ea4bc100-fb1c-11e9-87fe-3066ec6b1e6a.png">
is not the same as `CustomCSSBundle `

**Comment by inside54** [comment]
cache cleared https://puu.sh/EyJZu/b418bff543.png
directory fixed https://puu.sh/EyK0M/91ee23f08b.png

same result :(

**Comment by inside54** [comment]
thank you for your time, solved!
